"""
questions_m1.py — Module 1: Python Core
3 Practice sets + 1 Final assessment (moderate level)
Topics: Data types, control flow, data structures, functions, OOP, error handling
"""

import hashlib, re

def _norm(s): return re.sub(r'\s+', '', str(s).strip().lower())
def h(s):     return hashlib.sha256(_norm(s).encode()).hexdigest()

# ════════════════════════════════════════════════════════════════
# PRACTICE SET 1 — Data Types + Data Structures
# ════════════════════════════════════════════════════════════════
M1_PRACTICE_1 = [
    {"id":1,"type":"mcq","marks":2,
     "text":"What is the output of:\n\ntype(1/2) == type(1//2)",
     "opts":["True","False","TypeError","None"],
     "ah":h("False"),
     "solution":"print(type(1/2))   # float\nprint(type(1//2))  # int\nprint(type(1/2) == type(1//2))  # False",
     "explanation":"1/2 gives float (0.5), 1//2 gives int (0). Different types."},
    {"id":2,"type":"mcq","marks":2,
     "text":"Which of the following will raise a TypeError?",
     "opts":["'5' + '3'","'5' * 3","'5' + 3","str(5) + '3'"],
     "ah":h("'5' + 3"),
     "solution":"# '5' + 3 raises TypeError\n# Cannot add str and int directly\n# Fix: str(5) + '3'  or  '5' + str(3)",
     "explanation":"Python does not auto-convert types. Adding str + int raises TypeError."},
    {"id":3,"type":"fill","marks":2,
     "text":"What is the output of:\n\n[x for x in range(10) if x%2==0 and x%3==0]\n\nType exactly as Python would print it.",
     "ah":h("[0, 6]"),
     "exp":"[0, 6]",
     "solution":"result = [x for x in range(10) if x%2==0 and x%3==0]\nprint(result)  # [0, 6]",
     "explanation":"Numbers divisible by both 2 and 3 (i.e. by 6) in range 0-9: 0 and 6."},
    {"id":4,"type":"fill","marks":2,
     "text":"What is the output of:\n\n{k:v for k,v in zip('abcde', range(5))}\n\nType exactly as Python would print it.",
     "ah":h("{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}"),
     "exp":"{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}",
     "solution":"result = {k:v for k,v in zip('abcde', range(5))}\nprint(result)",
     "explanation":"zip pairs each character with its index. Dict comprehension builds the mapping."},
    {"id":5,"type":"fill","marks":3,
     "text":"Given:\n\nd = {'x':10, 'y':20, 'z':30}\n\nWhat does this return?\n\n{k:v for k,v in d.items() if v > 15}",
     "ah":h("{'y': 20, 'z': 30}"),
     "exp":"{'y': 20, 'z': 30}",
     "solution":"d = {'x':10, 'y':20, 'z':30}\nresult = {k:v for k,v in d.items() if v > 15}\nprint(result)  # {'y': 20, 'z': 30}",
     "explanation":"Filter dict items where value > 15. Only 'y':20 and 'z':30 qualify."},
    {"id":6,"type":"fill","marks":3,
     "text":"What is the output of:\n\nlist(map(lambda x: x**3, filter(lambda x: x%2==0, range(1,6))))\n\nType exactly as Python would print it.",
     "ah":h("[8, 64]"),
     "exp":"[8, 64]",
     "solution":"# Step 1: filter evens from 1-5 → [2, 4]\n# Step 2: cube each → [8, 64]\nresult = list(map(lambda x: x**3, filter(lambda x: x%2==0, range(1,6))))\nprint(result)",
     "explanation":"filter gets evens [2,4], map cubes them → [8, 64]."},
    {"id":7,"type":"code","marks":4,
     "text":"What is the output of this closure?\n\ndef outer(x):\n    def inner(y): return x + y\n    return inner\nadd5 = outer(5)\nprint(add5(3))",
     "preload":"","exp":"8",
     "solution":"def outer(x):\n    def inner(y): return x + y\n    return inner\nadd5 = outer(5)\nprint(add5(3))  # 8",
     "explanation":"outer(5) returns inner with x=5 captured. add5(3) returns 5+3=8."},
    {"id":8,"type":"code","marks":4,
     "text":"Preloaded:\n  data = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]\n\nWrite code to return a dict where keys are unique elements\nand values are their counts. Print sorted by key.",
     "preload":"data = [3,1,4,1,5,9,2,6,5,3,5]\n",
     "exp":"{1: 2, 2: 1, 3: 2, 4: 1, 5: 3, 6: 1, 9: 1}",
     "solution":"data = [3,1,4,1,5,9,2,6,5,3,5]\nresult = {x: data.count(x) for x in sorted(set(data))}\nprint(result)",
     "explanation":"set() gets unique values, count() gets frequency, sorted() orders by key."},
    {"id":9,"type":"code","marks":5,
     "text":"Write a function flatten(lst) that flattens a nested list of any depth.\n\nPreloaded:\n  nested = [1, [2, 3], [4, [5, 6]], 7]\n\nPrint the flattened result.",
     "preload":"nested = [1, [2, 3], [4, [5, 6]], 7]\n",
     "exp":"[1, 2, 3, 4, 5, 6, 7]",
     "solution":"def flatten(lst):\n    result = []\n    for item in lst:\n        if isinstance(item, list):\n            result.extend(flatten(item))\n        else:\n            result.append(item)\n    return result\n\nnested = [1, [2, 3], [4, [5, 6]], 7]\nprint(flatten(nested))",
     "explanation":"Recursive approach: if item is list, flatten it recursively; else append directly."},
]

# ════════════════════════════════════════════════════════════════
# PRACTICE SET 2 — Control Flow + Functions
# ════════════════════════════════════════════════════════════════
M1_PRACTICE_2 = [
    {"id":1,"type":"mcq","marks":2,
     "text":"What does this print?\n\nfor i in range(3):\n    pass\nelse:\n    print('done')",
     "opts":["done","nothing","error","0 1 2 done"],
     "ah":h("done"),
     "solution":"for i in range(3):\n    pass\nelse:\n    print('done')  # done",
     "explanation":"The else block on a for loop runs when the loop completes normally (not via break)."},
    {"id":2,"type":"mcq","marks":2,
     "text":"What is the output of:\n\nx = 5\nresult = 'high' if x > 3 else 'low' if x > 1 else 'zero'\nprint(result)",
     "opts":["high","low","zero","error"],
     "ah":h("high"),
     "solution":"x = 5\nresult = 'high' if x > 3 else 'low' if x > 1 else 'zero'\nprint(result)  # high",
     "explanation":"x=5 > 3 is True, so result='high'. Chained ternary evaluates left to right."},
    {"id":3,"type":"fill","marks":3,
     "text":"What is the output of:\n\nprint(sorted({3,1,4,1,5,9,2,6}))\n\nType exactly as Python would print it.",
     "ah":h("[1, 2, 3, 4, 5, 6, 9]"),
     "exp":"[1, 2, 3, 4, 5, 6, 9]",
     "solution":"print(sorted({3,1,4,1,5,9,2,6}))  # [1, 2, 3, 4, 5, 6, 9]",
     "explanation":"Set removes duplicates (1 appears once), sorted() returns a sorted list."},
    {"id":4,"type":"fill","marks":3,
     "text":"What is the output of:\n\nprint('hello'[::2])",
     "ah":h("hlo"),
     "exp":"hlo",
     "solution":"print('hello'[::2])  # hlo",
     "explanation":"[::2] takes every 2nd character: h(0), l(2), o(4)."},
    {"id":5,"type":"fill","marks":3,
     "text":"What does this print?\n\ndef func(a, b=2, *args, **kwargs):\n    print(a, b, args, kwargs)\nfunc(1, 3, 4, 5, x=6)",
     "ah":h("1 3 (4, 5) {'x': 6}"),
     "exp":"1 3 (4, 5) {'x': 6}",
     "solution":"def func(a, b=2, *args, **kwargs):\n    print(a, b, args, kwargs)\nfunc(1, 3, 4, 5, x=6)\n# a=1, b=3, args=(4,5), kwargs={'x':6}",
     "explanation":"1→a, 3→b (overrides default), 4,5→args tuple, x=6→kwargs dict."},
    {"id":6,"type":"fill","marks":4,
     "text":"What is the output of:\n\ndef counter():\n    count = 0\n    def inc():\n        nonlocal count\n        count += 1\n        return count\n    return inc\nc = counter()\nprint(c(), c(), c())",
     "ah":h("1 2 3"),
     "exp":"1 2 3",
     "solution":"def counter():\n    count = 0\n    def inc():\n        nonlocal count\n        count += 1\n        return count\n    return inc\nc = counter()\nprint(c(), c(), c())  # 1 2 3",
     "explanation":"nonlocal lets inner function modify outer variable. Each call increments count."},
    {"id":7,"type":"code","marks":4,
     "text":"Write a generator function fibonacci(n) that yields first n Fibonacci numbers.\n\nPreloaded: n = 10\n\nPrint the list of first 10 Fibonacci numbers.",
     "preload":"n = 10\n",
     "exp":"[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]",
     "solution":"def fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b\n\nn = 10\nprint(list(fibonacci(n)))",
     "explanation":"Generator yields one value at a time. a,b = b,a+b advances the sequence."},
    {"id":8,"type":"code","marks":4,
     "text":"Preloaded:\n  matrix = [[1,2,3],[4,5,6],[7,8,9]]\n\nTranspose the matrix using list comprehension.\nPrint the transposed matrix.",
     "preload":"matrix = [[1,2,3],[4,5,6],[7,8,9]]\n",
     "exp":"[[1, 4, 7], [2, 5, 8], [3, 6, 9]]",
     "solution":"matrix = [[1,2,3],[4,5,6],[7,8,9]]\ntransposed = [[row[i] for row in matrix] for i in range(len(matrix[0]))]\nprint(transposed)",
     "explanation":"For each column index i, collect matrix[row][i] across all rows."},
    {"id":9,"type":"code","marks":5,
     "text":"Write a function group_by(lst, key_func) that groups elements by key_func.\n\nPreloaded:\n  words = ['apple','ant','banana','bear','cherry','cat']\n\nGroup by first letter. Print sorted by key.",
     "preload":"words = ['apple','ant','banana','bear','cherry','cat']\n",
     "exp":"{'a': ['apple', 'ant'], 'b': ['banana', 'bear'], 'c': ['cherry', 'cat']}",
     "solution":"words = ['apple','ant','banana','bear','cherry','cat']\nresult = {}\nfor w in words:\n    key = w[0]\n    result.setdefault(key, []).append(w)\nprint(dict(sorted(result.items())))",
     "explanation":"setdefault creates empty list if key missing, then appends. sorted() orders by key."},
]

# ════════════════════════════════════════════════════════════════
# PRACTICE SET 3 — OOP + Error Handling
# ════════════════════════════════════════════════════════════════
M1_PRACTICE_3 = [
    {"id":1,"type":"mcq","marks":2,
     "text":"What is the output of:\n\nclass A:\n    x = 10\na = A()\na.x = 20\nprint(A.x, a.x)",
     "opts":["10 10","20 20","10 20","20 10"],
     "ah":h("10 20"),
     "solution":"class A:\n    x = 10\na = A()\na.x = 20\nprint(A.x, a.x)  # 10 20",
     "explanation":"a.x = 20 creates an instance attribute, not modifying class attribute A.x."},
    {"id":2,"type":"mcq","marks":2,
     "text":"What does @staticmethod mean in Python?",
     "opts":[
         "Method can only access class variables",
         "Method does not receive self or cls — belongs to the class namespace",
         "Method is called automatically on class creation",
         "Method cannot be overridden"
     ],
     "ah":h("Method does not receive self or cls — belongs to the class namespace"),
     "solution":"class MyClass:\n    @staticmethod\n    def greet():\n        return 'Hello'  # no self or cls needed\n\nprint(MyClass.greet())",
     "explanation":"staticmethod doesn't receive the instance or class automatically. It's a regular function namespaced inside the class."},
    {"id":3,"type":"fill","marks":3,
     "text":"What is the output of:\n\nsum(i for i in range(1, 101) if i%3==0 or i%5==0)",
     "ah":h("2418"),
     "exp":"2418",
     "solution":"result = sum(i for i in range(1, 101) if i%3==0 or i%5==0)\nprint(result)  # 2418",
     "explanation":"Sum all numbers from 1-100 divisible by 3 or 5. Classic FizzBuzz sum."},
    {"id":4,"type":"fill","marks":3,
     "text":"What does this print?\n\ntry:\n    x = int('abc')\nexcept ValueError:\n    print('value error')\nexcept Exception:\n    print('other error')\nfinally:\n    print('done')",
     "ah":h("value error\ndone"),
     "exp":"value error\ndone",
     "solution":"try:\n    x = int('abc')  # raises ValueError\nexcept ValueError:\n    print('value error')\nfinally:\n    print('done')  # always runs",
     "explanation":"int('abc') raises ValueError. finally block always executes regardless of exception."},
    {"id":5,"type":"fill","marks":3,
     "text":"What is the output of:\n\nclass MyClass:\n    def __init__(self): self.x = 0\n    def __add__(self, other): return self.x + other.x\na = MyClass(); a.x = 5\nb = MyClass(); b.x = 3\nprint(a + b)",
     "ah":h("8"),
     "exp":"8",
     "solution":"class MyClass:\n    def __init__(self): self.x = 0\n    def __add__(self, other): return self.x + other.x\na = MyClass(); a.x = 5\nb = MyClass(); b.x = 3\nprint(a + b)  # 8",
     "explanation":"__add__ is called when + is used. Returns a.x + b.x = 5 + 3 = 8."},
    {"id":6,"type":"fill","marks":4,
     "text":"What is the output of:\n\nclass Animal:\n    def __init__(self, name): self.name = name\nclass Dog(Animal):\n    def __init__(self, name, breed):\n        super().__init__(name)\n        self.breed = breed\nd = Dog('Rex', 'Lab')\nprint(d.name, d.breed)",
     "ah":h("Rex Lab"),
     "exp":"Rex Lab",
     "solution":"class Animal:\n    def __init__(self, name): self.name = name\nclass Dog(Animal):\n    def __init__(self, name, breed):\n        super().__init__(name)  # calls Animal.__init__\n        self.breed = breed\nd = Dog('Rex', 'Lab')\nprint(d.name, d.breed)  # Rex Lab",
     "explanation":"super().__init__(name) calls parent class constructor to set self.name."},
    {"id":7,"type":"code","marks":4,
     "text":"Write a class Stack with methods:\n  push(item), pop(), peek(), is_empty(), size()\n\nRun:\n  s = Stack()\n  s.push(1); s.push(2); s.push(3)\n  print(s.peek())\n  s.pop()\n  print(s.size())",
     "preload":"",
     "exp":"3\n2",
     "solution":"class Stack:\n    def __init__(self): self._data = []\n    def push(self, item): self._data.append(item)\n    def pop(self): return self._data.pop()\n    def peek(self): return self._data[-1]\n    def is_empty(self): return len(self._data) == 0\n    def size(self): return len(self._data)\n\ns = Stack()\ns.push(1); s.push(2); s.push(3)\nprint(s.peek())  # 3\ns.pop()\nprint(s.size())  # 2",
     "explanation":"Stack uses a list internally. peek() returns last item without removing it."},
    {"id":8,"type":"code","marks":4,
     "text":"Write a context manager class Timer using __enter__ and __exit__.\nIt should print 'start' on enter and 'end' on exit.\n\nRun:\n  with Timer():\n      pass",
     "preload":"",
     "exp":"start\nend",
     "solution":"class Timer:\n    def __enter__(self):\n        print('start')\n        return self\n    def __exit__(self, *args):\n        print('end')\n\nwith Timer():\n    pass",
     "explanation":"__enter__ runs on with block entry, __exit__ runs on exit (even if exception)."},
    {"id":9,"type":"code","marks":5,
     "text":"Implement a LRU Cache class with capacity=2.\nMethods: get(key) returns -1 if not found, put(key, value).\n\nRun:\n  cache = LRUCache(2)\n  cache.put(1, 1)\n  cache.put(2, 2)\n  print(cache.get(1))\n  cache.put(3, 3)\n  print(cache.get(2))",
     "preload":"",
     "exp":"1\n-1",
     "solution":"from collections import OrderedDict\nclass LRUCache:\n    def __init__(self, capacity):\n        self.cap = capacity\n        self.cache = OrderedDict()\n    def get(self, key):\n        if key not in self.cache: return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n    def put(self, key, value):\n        if key in self.cache: self.cache.move_to_end(key)\n        self.cache[key] = value\n        if len(self.cache) > self.cap:\n            self.cache.popitem(last=False)\n\ncache = LRUCache(2)\ncache.put(1,1); cache.put(2,2)\nprint(cache.get(1))   # 1\ncache.put(3,3)        # evicts key 2\nprint(cache.get(2))   # -1",
     "explanation":"OrderedDict maintains insertion order. move_to_end marks as recently used. popitem(last=False) evicts least recently used."},
]

# ════════════════════════════════════════════════════════════════
# FINAL ASSESSMENT — Moderate level, MCQ + Coding only
# ════════════════════════════════════════════════════════════════
M1_FINAL = [
    {"id":1,"type":"mcq","marks":3,
     "text":"What will this print?\n\nx = [1, 2, 3]\ny = x\ny.append(4)\nprint(x)",
     "opts":["[1, 2, 3]","[1, 2, 3, 4]","[4]","Error"],
     "ah":h("[1, 2, 3, 4]"),
     "solution":"x = [1, 2, 3]\ny = x        # y points to same list\ny.append(4)\nprint(x)     # [1, 2, 3, 4]",
     "explanation":"y = x doesn't copy — both variables point to the same list object. Mutating via y affects x."},
    {"id":2,"type":"mcq","marks":3,
     "text":"What is the average time complexity of looking up a key in a Python dictionary?",
     "opts":["O(n)","O(log n)","O(1)","O(n²)"],
     "ah":h("O(1)"),
     "solution":"# Dicts use hash tables\n# Hash is computed → direct memory access\n# Average case: O(1)\n# Worst case (hash collisions): O(n) — rare",
     "explanation":"Python dicts use hash tables providing O(1) average lookup. Hash collisions make worst case O(n) but this is rare."},
    {"id":3,"type":"mcq","marks":3,
     "text":"What does this print?\n\nfor i in range(5):\n    if i == 3:\n        break\nelse:\n    print('no break')\nprint('done')",
     "opts":["no break\ndone","done","no break","Error"],
     "ah":h("done"),
     "solution":"for i in range(5):\n    if i == 3:\n        break   # loop exits via break\nelse:\n    print('no break')  # skipped — break was hit\nprint('done')  # always runs",
     "explanation":"The else block only runs if the loop completes without break. Since break fires at i=3, else is skipped."},
    {"id":4,"type":"mcq","marks":3,
     "text":"Which of the following creates a shallow copy of a list?",
     "opts":["y = x","y = x.copy()","y = x.deepcopy()","y = list.copy(x, deep=True)"],
     "ah":h("y = x.copy()"),
     "solution":"import copy\nx = [1, [2, 3]]\ny = x.copy()       # shallow copy\nz = copy.deepcopy(x)  # deep copy",
     "explanation":"x.copy() creates a new list but nested objects are still shared. deepcopy() copies everything recursively."},
    {"id":5,"type":"code","marks":4,
     "text":"Write a function sum_evens(numbers) that returns the sum of all even numbers in a list.\n\nPreloaded:\n  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n\nPrint the result.",
     "preload":"numbers = [1,2,3,4,5,6,7,8,9,10]\n",
     "exp":"30",
     "solution":"def sum_evens(numbers):\n    return sum(x for x in numbers if x % 2 == 0)\n\nnumbers = [1,2,3,4,5,6,7,8,9,10]\nprint(sum_evens(numbers))  # 30",
     "explanation":"Generator expression filters evens, sum() totals them: 2+4+6+8+10=30."},
    {"id":6,"type":"code","marks":4,
     "text":"Write a function count_words(sentence) that returns a dict of word frequencies.\n\nPreloaded:\n  sentence = 'the cat sat on the mat the cat'\n\nPrint sorted by key.",
     "preload":"sentence = 'the cat sat on the mat the cat'\n",
     "exp":"{'cat': 2, 'mat': 1, 'on': 1, 'sat': 1, 'the': 3}",
     "solution":"def count_words(sentence):\n    words = sentence.split()\n    return {w: words.count(w) for w in sorted(set(words))}\n\nsentence = 'the cat sat on the mat the cat'\nprint(count_words(sentence))",
     "explanation":"split() tokenises, set() deduplicates, count() tallies frequency per word."},
    {"id":7,"type":"code","marks":4,
     "text":"Write a function is_palindrome(s) that returns True if s is a palindrome, ignoring case and spaces.\n\nPreloaded:\n  test1 = 'A man a plan a canal Panama'\n  test2 = 'hello'\n\nPrint result for both.",
     "preload":"test1 = 'A man a plan a canal Panama'\ntest2 = 'hello'\n",
     "exp":"True\nFalse",
     "solution":"def is_palindrome(s):\n    cleaned = s.replace(' ', '').lower()\n    return cleaned == cleaned[::-1]\n\ntest1 = 'A man a plan a canal Panama'\ntest2 = 'hello'\nprint(is_palindrome(test1))  # True\nprint(is_palindrome(test2))  # False",
     "explanation":"Remove spaces, lowercase, compare with reverse. [::-1] reverses a string."},
    {"id":8,"type":"code","marks":4,
     "text":"Write a class Rectangle with:\n  - __init__(width, height)\n  - area() method\n  - perimeter() method\n  - __str__ returning 'Rectangle(w x h)'\n\nRun:\n  r = Rectangle(4, 5)\n  print(r.area())\n  print(r.perimeter())\n  print(r)",
     "preload":"",
     "exp":"20\n18\nRectangle(4 x 5)",
     "solution":"class Rectangle:\n    def __init__(self, width, height):\n        self.width = width\n        self.height = height\n    def area(self): return self.width * self.height\n    def perimeter(self): return 2 * (self.width + self.height)\n    def __str__(self): return f'Rectangle({self.width} x {self.height})'\n\nr = Rectangle(4, 5)\nprint(r.area())       # 20\nprint(r.perimeter())  # 18\nprint(r)              # Rectangle(4 x 5)",
     "explanation":"__str__ controls how the object prints. area=w*h, perimeter=2*(w+h)."},
    {"id":9,"type":"code","marks":4,
     "text":"Write a function safe_divide(a, b) that:\n  - Returns a/b if b != 0\n  - Returns None if b == 0\n  - Raises TypeError with message 'Inputs must be numbers' if either is not int/float\n\nRun:\n  print(safe_divide(10, 2))\n  print(safe_divide(10, 0))\n  try:\n      safe_divide('a', 2)\n  except TypeError as e:\n      print(e)",
     "preload":"",
     "exp":"5.0\nNone\nInputs must be numbers",
     "solution":"def safe_divide(a, b):\n    if not isinstance(a, (int, float)) or not isinstance(b, (int, float)):\n        raise TypeError('Inputs must be numbers')\n    return a / b if b != 0 else None\n\nprint(safe_divide(10, 2))   # 5.0\nprint(safe_divide(10, 0))   # None\ntry:\n    safe_divide('a', 2)\nexcept TypeError as e:\n    print(e)                 # Inputs must be numbers",
     "explanation":"isinstance checks type, returns None for zero division, raises TypeError for wrong types."},
    {"id":10,"type":"code","marks":5,
     "text":"Preloaded:\n  students = [\n    {'name': 'Alice', 'score': 85, 'grade': 'A'},\n    {'name': 'Bob', 'score': 72, 'grade': 'B'},\n    {'name': 'Charlie', 'score': 91, 'grade': 'A'},\n    {'name': 'Diana', 'score': 68, 'grade': 'B'},\n    {'name': 'Eve', 'score': 95, 'grade': 'A'},\n  ]\n\nWrite code to:\n1. Find average score of grade 'A' students\n2. Print rounded to 2 decimal places",
     "preload":"students = [{'name':'Alice','score':85,'grade':'A'},{'name':'Bob','score':72,'grade':'B'},{'name':'Charlie','score':91,'grade':'A'},{'name':'Diana','score':68,'grade':'B'},{'name':'Eve','score':95,'grade':'A'}]\n",
     "exp":"90.33",
     "solution":"students = [{'name':'Alice','score':85,'grade':'A'},{'name':'Bob','score':72,'grade':'B'},{'name':'Charlie','score':91,'grade':'A'},{'name':'Diana','score':68,'grade':'B'},{'name':'Eve','score':95,'grade':'A'}]\na_students = [s['score'] for s in students if s['grade'] == 'A']\nprint(round(sum(a_students) / len(a_students), 2))  # 90.33",
     "explanation":"Filter grade A students, extract scores, compute mean: (85+91+95)/3 = 90.33."},
    {"id":11,"type":"mcq","marks":3,
     "text":"What is the output of:\n\ndef func(x, y=5):\n    return x * y\nprint(func(3))\nprint(func(3, 2))",
     "opts":["15\n6","3\n6","15\n5","Error"],
     "ah":h("15\n6"),
     "solution":"def func(x, y=5):\n    return x * y\nprint(func(3))     # 3*5 = 15\nprint(func(3, 2))  # 3*2 = 6",
     "explanation":"Default parameter y=5 is used when not provided. func(3) → 3*5=15, func(3,2) → 3*2=6."},
    {"id":12,"type":"mcq","marks":3,
     "text":"Which statement about Python sets is correct?",
     "opts":[
         "Sets allow duplicate values",
         "Sets are ordered and indexed",
         "Sets are unordered and contain only unique values",
         "Sets support indexing like lists"
     ],
     "ah":h("Sets are unordered and contain only unique values"),
     "solution":"s = {1, 2, 2, 3}\nprint(s)       # {1, 2, 3} — no duplicates\nprint(type(s)) # <class 'set'>\n# s[0] → TypeError: sets don't support indexing",
     "explanation":"Sets store only unique values and have no guaranteed order. No indexing supported."},
]

# ── MAPS ─────────────────────────────────────────────────────────
M1_PRACTICE_TESTS = {1: M1_PRACTICE_1, 2: M1_PRACTICE_2, 3: M1_PRACTICE_3}
M1_FINAL_TEST     = {1: M1_FINAL}
